from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu_Win(object):
    def setupUi(self, Menu_Win):
        Menu_Win.setObjectName("Menu_Win")
        Menu_Win.resize(800, 524)
        self.menu_win = QtWidgets.QWidget(Menu_Win)
        self.menu_win.setObjectName("menu_win")

        self.menu_lbl = QtWidgets.QLabel(self.menu_win)
        self.menu_lbl.setGeometry(QtCore.QRect(20, 10, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.menu_lbl.setFont(font)
        self.menu_lbl.setObjectName("menu_lbl")

        self.koshari_lbl = QtWidgets.QLabel(self.menu_win)
        self.koshari_lbl.setGeometry(QtCore.QRect(30, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.koshari_lbl.setFont(font)
        self.koshari_lbl.setObjectName("koshari_lbl")

        self.add_kosh_btn = QtWidgets.QPushButton(self.menu_win)
        self.add_kosh_btn.setGeometry(QtCore.QRect(350, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.add_kosh_btn.setFont(font)
        self.add_kosh_btn.setObjectName("add_kosh_btn")

        self.rmv_mnu_btn = QtWidgets.QPushButton(self.menu_win)
        self.rmv_mnu_btn.setGeometry(QtCore.QRect(560, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.rmv_mnu_btn.setFont(font)
        self.rmv_mnu_btn.setObjectName("rmv_mnu_btn")

        self.add_kebda_btn = QtWidgets.QPushButton(self.menu_win)
        self.add_kebda_btn.setGeometry(QtCore.QRect(350, 190, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.add_kebda_btn.setFont(font)
        self.add_kebda_btn.setObjectName("add_kebda_btn")

        self.kebda_lbl = QtWidgets.QLabel(self.menu_win)
        self.kebda_lbl.setGeometry(QtCore.QRect(30, 190, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.kebda_lbl.setFont(font)
        self.kebda_lbl.setObjectName("kebda_lbl")

        self.rmv_mnu_btn_3 = QtWidgets.QPushButton(self.menu_win)
        self.rmv_mnu_btn_3.setGeometry(QtCore.QRect(560, 190, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.rmv_mnu_btn_3.setFont(font)
        self.rmv_mnu_btn_3.setObjectName("rmv_mnu_btn_3")

        self.add_foul_btn = QtWidgets.QPushButton(self.menu_win)
        self.add_foul_btn.setGeometry(QtCore.QRect(350, 290, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.add_foul_btn.setFont(font)
        self.add_foul_btn.setObjectName("add_foul_btn")

        self.foul_lbl = QtWidgets.QLabel(self.menu_win)
        self.foul_lbl.setGeometry(QtCore.QRect(30, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.foul_lbl.setFont(font)
        self.foul_lbl.setObjectName("foul_lbl")

        self.rmv_mnu_btn_6 = QtWidgets.QPushButton(self.menu_win)
        self.rmv_mnu_btn_6.setGeometry(QtCore.QRect(560, 290, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.rmv_mnu_btn_6.setFont(font)
        self.rmv_mnu_btn_6.setObjectName("rmv_mnu_btn_6")

        self.add_flafel_btn = QtWidgets.QPushButton(self.menu_win)
        self.add_flafel_btn.setGeometry(QtCore.QRect(350, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.add_flafel_btn.setFont(font)
        self.add_flafel_btn.setObjectName("add_flafel_btn")

        self.flafel_lbl = QtWidgets.QLabel(self.menu_win)
        self.flafel_lbl.setGeometry(QtCore.QRect(30, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.flafel_lbl.setFont(font)
        self.flafel_lbl.setObjectName("flafel_lbl")

        self.rmv_mnu_btn_5 = QtWidgets.QPushButton(self.menu_win)
        self.rmv_mnu_btn_5.setGeometry(QtCore.QRect(560, 340, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.rmv_mnu_btn_5.setFont(font)
        self.rmv_mnu_btn_5.setObjectName("rmv_mnu_btn_5")

        self.add_pizza_btn = QtWidgets.QPushButton(self.menu_win)
        self.add_pizza_btn.setGeometry(QtCore.QRect(350, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.add_pizza_btn.setFont(font)
        self.add_pizza_btn.setObjectName("add_pizza_btn")

        self.pizza_lbl = QtWidgets.QLabel(self.menu_win)
        self.pizza_lbl.setGeometry(QtCore.QRect(30, 240, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.pizza_lbl.setFont(font)
        self.pizza_lbl.setObjectName("pizza_lbl")

        self.rmv_mnu_btn_4 = QtWidgets.QPushButton(self.menu_win)
        self.rmv_mnu_btn_4.setGeometry(QtCore.QRect(560, 240, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.rmv_mnu_btn_4.setFont(font)
        self.rmv_mnu_btn_4.setObjectName("rmv_mnu_btn_4")

        self.add_fried_btn = QtWidgets.QPushButton(self.menu_win)
        self.add_fried_btn.setGeometry(QtCore.QRect(350, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.add_fried_btn.setFont(font)
        self.add_fried_btn.setObjectName("add_fried_btn")

        self.fried_potatos_lbl = QtWidgets.QLabel(self.menu_win)
        self.fried_potatos_lbl.setGeometry(QtCore.QRect(30, 140, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.fried_potatos_lbl.setFont(font)
        self.fried_potatos_lbl.setObjectName("fried_potatos_lbl")

        self.rmv_mnu_btn_2 = QtWidgets.QPushButton(self.menu_win)
        self.rmv_mnu_btn_2.setGeometry(QtCore.QRect(560, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.rmv_mnu_btn_2.setFont(font)
        self.rmv_mnu_btn_2.setObjectName("rmv_mnu_btn_2")

        self.shw_ord_btn = QtWidgets.QPushButton(self.menu_win)
        self.shw_ord_btn.setGeometry(QtCore.QRect(600, 450, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.shw_ord_btn.setFont(font)
        self.shw_ord_btn.setObjectName("shw_ord_btn")
        
        self.cnl_ord_btn = QtWidgets.QPushButton(self.menu_win)
        self.cnl_ord_btn.setGeometry(QtCore.QRect(70, 450, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        self.cnl_ord_btn.setFont(font)
        self.cnl_ord_btn.setObjectName("cnl_ord_btn")
        self.kosh_spinBox = QtWidgets.QSpinBox(self.menu_win)
        self.kosh_spinBox.setGeometry(QtCore.QRect(260, 90, 51, 31))
        self.kosh_spinBox.setObjectName("kosh_spinBox")
        self.fried_spinBox = QtWidgets.QSpinBox(self.menu_win)
        self.fried_spinBox.setGeometry(QtCore.QRect(260, 140, 51, 31))
        self.fried_spinBox.setObjectName("fried_spinBox")
        self.Kebda_spinBox = QtWidgets.QSpinBox(self.menu_win)
        self.Kebda_spinBox.setGeometry(QtCore.QRect(260, 190, 51, 31))
        self.Kebda_spinBox.setObjectName("Kebda_spinBox")
        self.pizza_spinBox = QtWidgets.QSpinBox(self.menu_win)
        self.pizza_spinBox.setGeometry(QtCore.QRect(260, 240, 51, 31))
        self.pizza_spinBox.setObjectName("pizza_spinBox")
        self.foul_spinBox = QtWidgets.QSpinBox(self.menu_win)
        self.foul_spinBox.setGeometry(QtCore.QRect(260, 290, 51, 31))
        self.foul_spinBox.setObjectName("foul_spinBox")
        self.flafel_spinBox = QtWidgets.QSpinBox(self.menu_win)
        self.flafel_spinBox.setGeometry(QtCore.QRect(260, 340, 51, 31))
        self.flafel_spinBox.setObjectName("flafel_spinBox")
        
        Menu_Win.setCentralWidget(self.menu_win)

        self.retranslateUi(Menu_Win)
        QtCore.QMetaObject.connectSlotsByName(Menu_Win)

    def retranslateUi(self, Menu_Win):
        _translate = QtCore.QCoreApplication.translate
        Menu_Win.setWindowTitle(_translate("Menu_Win", "MainWindow"))
        self.menu_lbl.setText(_translate("Menu_Win", "MENU"))
        self.koshari_lbl.setText(_translate("Menu_Win", "Koshari"))
        self.add_kosh_btn.setText(_translate("Menu_Win", "Add To Order"))
        self.rmv_mnu_btn.setText(_translate("Menu_Win", "Remove From Order"))
        self.add_kebda_btn.setText(_translate("Menu_Win", "Add To Order"))
        self.kebda_lbl.setText(_translate("Menu_Win", "Kebda"))
        self.rmv_mnu_btn_3.setText(_translate("Menu_Win", "Remove From Order"))
        self.add_foul_btn.setText(_translate("Menu_Win", "Add To Order"))
        self.foul_lbl.setText(_translate("Menu_Win", "Foul"))
        self.rmv_mnu_btn_6.setText(_translate("Menu_Win", "Remove From Order"))
        self.add_flafel_btn.setText(_translate("Menu_Win", "Add To Order"))
        self.flafel_lbl.setText(_translate("Menu_Win", "Flafel"))
        self.rmv_mnu_btn_5.setText(_translate("Menu_Win", "Remove From Order"))
        self.add_pizza_btn.setText(_translate("Menu_Win", "Add To Order"))
        self.pizza_lbl.setText(_translate("Menu_Win", "Pizza"))
        self.rmv_mnu_btn_4.setText(_translate("Menu_Win", "Remove From Order"))
        self.add_fried_btn.setText(_translate("Menu_Win", "Add To Order"))
        self.fried_potatos_lbl.setText(_translate("Menu_Win", "Fried Potatos"))
        self.rmv_mnu_btn_2.setText(_translate("Menu_Win", "Remove From Order"))
        self.shw_ord_btn.setText(_translate("Menu_Win", "Show Order"))
        self.cnl_ord_btn.setText(_translate("Menu_Win", "Cancel Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu_Win = QtWidgets.QMainWindow()
    ui = Ui_Menu_Win()
    ui.setupUi(Menu_Win)
    Menu_Win.show()
    sys.exit(app.exec_())
